[tool.poetry]
name = "sudoku"
version = "0.1.3"
description = "Simple Sudoku App"
authors = ["JohN100x1@hotmail.co.uk"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79