name: Tests

on: push

jobs:
  build:
    name: Setup Python Poetry Project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest

      - name: Run black
        run: poetry run black . --check

      - name: Run isort
        run: poetry run isort . --check